Fix DOCKER_TAG on package-registry distribution copy to dockerhub (#1728)
Fix package-registry distribution step to use DOCKER_TAG effectively

diff --git a/.buildkite/release-package-registry-distribution.yml b/.buildkite/release-package-registry-distribution.yml
--- a/.buildkite/release-package-registry-distribution.yml
+++ b/.buildkite/release-package-registry-distribution.yml
@@ -55,9 +55,13 @@ steps:
     command: |
         set -euo pipefail
 
-        DOCKER_TAG="$(buildkite-agent meta-data get DOCKER_TAG)"
+        DOCKER_TAG="$$(buildkite-agent meta-data get DOCKER_TAG --default="")"
+        if [[ -z "$${DOCKER_TAG:-""}" ]]; then
+            echo "ERROR: DOCKER_TAG meta-data is empty or not set"
+            exit 1
+        fi
 
-        cat <<YAML | buildkite-agent pipeline upload
+        buildkite-agent pipeline upload << PIPELINE
         steps:
           - trigger: unified-release-copy-elastic-images-to-dockerhub
             label: ":docker: Copy release images to Docker Hub"
@@ -66,7 +70,7 @@ steps:
             build:
               env:
                 IMAGES_NAMES: "package-registry/distribution"
-                IMAGES_TAG: "${DOCKER_TAG}"
+                IMAGES_TAG: "$${DOCKER_TAG}"
           - trigger: unified-release-copy-elastic-images-to-dockerhub
             label: ":docker: Copy release UBI images to Docker Hub"
             key: copy-prod-ubi
@@ -74,7 +78,7 @@ steps:
             build:
               env:
                 IMAGES_NAMES: "package-registry/distribution"
-                IMAGES_TAG: "${DOCKER_TAG}-ubi"
+                IMAGES_TAG: "$${DOCKER_TAG}-ubi"
           - trigger: unified-release-copy-elastic-images-to-dockerhub
             label: ":docker: Copy release lite images to Docker Hub"
             key: copy-lite
@@ -82,7 +86,7 @@ steps:
             build:
               env:
                 IMAGES_NAMES: "package-registry/distribution"
-                IMAGES_TAG: "lite-${DOCKER_TAG}"
+                IMAGES_TAG: "lite-$${DOCKER_TAG}"
           - trigger: unified-release-copy-elastic-images-to-dockerhub
             label: ":docker: Copy release lite UBI images to Docker Hub"
             key: copy-lite-ubi
@@ -90,8 +94,8 @@ steps:
             build:
               env:
                 IMAGES_NAMES: "package-registry/distribution"
-                IMAGES_TAG: "lite-${DOCKER_TAG}-ubi"
-        YAML
+                IMAGES_TAG: "lite-$${DOCKER_TAG}-ubi"
+        PIPELINE
     depends_on:
       - step: "release-distribution"
         allow_failure: false
